### ISSUE TITLE
Change on 17/09  from opencollective.com to images.opencolllective.com adds redirect

### ISSUE THREAD

**Issue by dougsillars** [opencollective/opencollective-images#10]
For example: see https://webpack.js.org/ (WebPageTest report here: https://www.webpagetest.org/result/181023_JP_b9476f132f954277f10ab45938be4702/)

Requests to:
 https://opencollective.com/proxy/images/? 
are 302 redirected to: 
https://images.opencollective.com/proxy/images/?
Well over 600 on this one page.

Further, the 302 redirects are not cached at Cloudfront:
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
so the redirect occurs on subsequent visits (see the repeat view in the WebPageTest report above).

**Comment by znarf** [comment]
Long term, I think we will serve better these images from a separate domain and this is why this was introduced.

How can we help you pointing directly to `images.opencollective.com` and not `opencollective.com`? Are you constructing the URL programmatically, or are you using data from an API endpoint?

**Comment by dougsillars** [comment]
That totally makes sense.  I am not on the webpack team - I just saw their website had an issue.  I think they are using an opencollective API to obtain the list of avatars, and that API is returning the url that gives the redirect.  

I see in their code a call to https://opencollective.com/api/groups/webpack/backers

this returns a JSON file with:
"avatar": "https://opencollective.com/proxy/images/?src=https%3A%2F%2Fopencollective-production.s3-us-west-1.amazonaws.com%2FWkzpfXkndvyjvIsIDo0U3_YbDn1dYi1dgTCmIagpx1H_L7kdcQHfnknyB7Q9INN1Es_w300_gxtuzepng_eb59bcd0-8672-11e7-b225-4ba72c1ef64e.png&height=96"

Which they use.  and then there is a redirect.

**Comment by znarf** [comment]
Thank you for the input. We're gonna change that asap.

**Comment by znarf** [comment]
This should be handled by:
https://github.com/opencollective/opencollective-api/pull/1497
